### PR TITLE
Dockerized tails-server now bases on newer version of von-image.

### PR DESCRIPTION
**Pull request by pixelschnitzel**
Applied change to run with Python 3.6. Also include indy_vdr. All changes were suggested in issue#17.

### CODE REVIEW

**Comment by swcurran** [comment]
@pixelschnitzel -- we need to have all commits signed for DCO (DCO - Developer Certificate of Origin - https://github.com/apps/dco). Please see the instructions for addressing on the "Details" link above, beside the failed DCO check.

**Comment by swcurran** [comment]
@andrewwhitehead -- can you please take a look at this?  Thanks!

**Comment by swcurran** [comment]
@WadeBarnes -- this PR got left behind. Given the updates you have been making recently -- is this still relevant?

**Comment by WadeBarnes** [comment]
I think the changes I'll be making will have a similar end result.  I'll be updating a few other components in the image as well.

**Comment by esune** [comment]
@WadeBarnes do we want to resolve conflicts and move this forward, or are we better off closing and waiting for the other work to be completed?

**Comment by WadeBarnes** [comment]
At this point I think we should close this and work on upgrading to a Python 3.9 based base image, similar to what's being done in [aries-cloudagent-python](https://github.com/hyperledger/aries-cloudagent-python) now.

**Pull request closed without merging**
