### PR TITLE
Update base image for tails-server from von-image to Python to simplify the image

### PR DESCRIPTION
**Pull request by pradeepp88**
This PR is to update the base image used for running the tails-server docker container from von-image to Python3.9. I have also added the missing dependencies `indy_vdr` and `python3_indy` to include in requirements and requirements.dev to run the server and tests.
Looking for feedback from the community.

### CODE REVIEW

**Comment by esune** [comment]
The integration tests do not seem to execute correctly, but I am having issues running them also from the `main` branch.
@pradeepp88 were you able to run the tests?

**Comment by pradeepp88** [comment]
@esune I ran the tests locally and found that the `indy_vdr` and `python3_indy` dependencies were missing in requirements.txt and requirements.dev.txt and you need to pass the `--tails-server-url` and `--genesis-url` arguments pointing to bcovrin test network when you run it locally with integration.py.

I also tried running the tests from the docker image with `./manage test`, I missed that the tests require indy-sdk installed locally as well, so we need to go back to von-image for that. Also we need the von-network running locally, and register the test seed `00000000000000000000000000000000` used in the integration test with endorser role for it to work. I have submitted a commit updating these changes in Readme and Dockerfile.test. Please check and let me know of your comments, thanks.

**Comment by pradeepp88** [comment]
@esune As discussed, I added the registration of DID step into the integration tests with `indy_vdr` and updated the README to start von-network before running the tests. This will spin up the integration tests automatically. Please check, thanks.

**Comment by esune** [comment]
@pradeepp88 thanks! The integration tests are now passing, I am going to run a real-life scenario out of caution and approve/merge if it works there as well.

**Comment by esune** [comment]
@WadeBarnes tested locally and was able to publish a tails file successfully. I think this is good to go, let me know if you think we should do more testing before merging.

**Review by esune — APPROVED** [review]

**Pull request merged**
